package io.project.wolfgymbot.service;

public enum DialogState {
    WAITING_EXERCISE_NAME_FOR_SEARCH,
    WAITING_EXERCISE_NAME,
    WAITING_EXERCISE_DESC,
    WAITING_EXERCISE_VIDEO_URL,
    WAITING_EXERCISE_MUSCLE_GROUP,
    EMPTY,
    START_CREATE_EXERCISE,
    CONFIRM_CREATE_EXERCISE,
    END_CREATE_EXERCISE,
    START_CREATE_WT,
    WAITING_WT_NAME,
    WAITING_WT_DESC,
    WAITING_WT_EXERCISES,
    CONFIRM_WT_CREATE,
    CANCEL_WT_CREATE,
    SKIP_WT_DESC
}
